name: Translate ressources

on:
  pull_request:
    branches: [ master ]

jobs:
  translation:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:

    # Checkout action manually bc branch is not merged
    - name: checkout cmi-xliff-tool
      uses: actions/checkout@v2
      with: 
        repository: CMInformatik/cmi-xliff-tool
        ref: feature/NO-TICKET_xliff_2_1
        token: ${{ secrets.PAT_TOKEN }}
        path: ./.github/cmi-xliff-tool

    - name: checkout code
      uses: actions/checkout@v2

    - name: translate
      uses: ./.github/cmi-xliff-tool
      with:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
        TRANSLATION_ROOT: ./src
        COMMIT_MESSAGE: Translations

